apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: pradyot09/eurekaserver:0.0.1
          ports:
            - containerPort: 9002
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver-service:9002/eureka/
            - name: SPRING_APPLICATION_NAME
              value: eurekaserver
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
---