apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: pradyot09/cards:0.0.1
          ports:
            - containerPort: 9004
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver-service:9002/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin-service:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: cards
---
apiVersion: v1
kind: Service
metadata:
  name: cards-service
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
---