apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: pradyot09/loans:0.0.1
          ports:
            - containerPort: 9005
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver-service:9002/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin-service:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: loans
---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
---