apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: pradyot09/gateway-server:0.0.1
          ports:
            - containerPort: 9001
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver-service:9002/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin-service:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: gateway-server
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
---